#ifndef LOCAL_POLICY_HPP
#define LOCAL_POLICY_HPP

#include <Arduino.h>
#include <array>
#include <cstdint>
#include <FS.h>
#include <LittleFS.h>
#include "deploy_config.h"
#include "local_obs_config.h"

// ===== Local policy network dimensions =====
// Input: latent_cmd(LOCAL_LATENT_DIM) + local_obs(LOCAL_OBS_DIM)
// Architecture: Linear(input->H1) -> ReLU -> Linear(H1->H2) -> ReLU -> Linear(H2->1)
// Output: 1 (mean only)
//
// Auto-generated by convert_local_policy_to_bin.py
// Activation: ReLU

constexpr size_t LOCAL_INPUT_DIM   = LOCAL_LATENT_DIM + LOCAL_OBS_DIM;
constexpr size_t LOCAL_H1_DIM      = DEPLOY_LOCAL_H1_DIM;
constexpr size_t LOCAL_H2_DIM      = DEPLOY_LOCAL_H2_DIM;
constexpr size_t LOCAL_ACT_DIM     = 1;

constexpr float LOCAL_ACTION_LOW  = DEPLOY_ACTION_LOW;
constexpr float LOCAL_ACTION_HIGH = DEPLOY_ACTION_HIGH;
constexpr float LOCAL_CLIP_MEAN   = DEPLOY_CLIP_MEAN;

// ===== Activation function =====
// ReLU activation: f(x) = max(0, x)
inline float local_activation(float x) {
    return (x > 0.0f) ? x : 0.0f;
}

inline uint32_t fnv1a31_update(uint32_t hash_value, const uint8_t* data, size_t len) {
    for (size_t i = 0; i < len; ++i) {
        hash_value ^= data[i];
        hash_value *= 16777619u;
    }
    return hash_value;
}

// ===== Fully-connected (dense) layer =====
template <size_t InputSize, size_t OutputSize>
class LocalFC {
public:
    LocalFC() : weights(nullptr), biases(nullptr) {}

    ~LocalFC() {
        if (weights) free(weights);
        if (biases) free(biases);
    }

    bool load(const char* weights_path, const char* biases_path) {
        if (!weights) {
            weights = (float*)ps_malloc(InputSize * OutputSize * sizeof(float));
            if (!weights) {
                Serial.println("    WARNING: PSRAM alloc failed, trying heap...");
                weights = (float*)malloc(InputSize * OutputSize * sizeof(float));
                if (!weights) {
                    Serial.printf("    ERROR: Failed to allocate %u bytes for weights\n",
                                  (unsigned)(InputSize * OutputSize * sizeof(float)));
                    return false;
                }
            }
        }
        if (!biases) {
            biases = (float*)ps_malloc(OutputSize * sizeof(float));
            if (!biases) {
                biases = (float*)malloc(OutputSize * sizeof(float));
                if (!biases) {
                    Serial.printf("    ERROR: Failed to allocate %u bytes for biases\n",
                                  (unsigned)(OutputSize * sizeof(float)));
                    return false;
                }
            }
        }
        {
            File f = LittleFS.open(weights_path, "r");
            if (!f) {
                Serial.printf("    ERROR: Cannot open %s\n", weights_path);
                return false;
            }
            const size_t nbytes = InputSize * OutputSize * sizeof(float);
            if (f.size() != nbytes) {
                Serial.printf("    ERROR: %s size %u != expected %u\n",
                              weights_path, (unsigned)f.size(), (unsigned)nbytes);
                f.close();
                return false;
            }
            int rd = f.readBytes(reinterpret_cast<char*>(weights), nbytes);
            f.close();
            if (rd != (int)nbytes) return false;
        }
        {
            File f = LittleFS.open(biases_path, "r");
            if (!f) {
                Serial.printf("    ERROR: Cannot open %s\n", biases_path);
                return false;
            }
            const size_t nbytes = OutputSize * sizeof(float);
            if (f.size() != nbytes) {
                Serial.printf("    ERROR: %s size %u != expected %u\n",
                              biases_path, (unsigned)f.size(), (unsigned)nbytes);
                f.close();
                return false;
            }
            int rd = f.readBytes(reinterpret_cast<char*>(biases), nbytes);
            f.close();
            if (rd != (int)nbytes) return false;
        }
        return true;
    }

    template <size_t N>
    void forward(const std::array<float, InputSize>& x,
                 std::array<float, N>& y) const {
        static_assert(N == OutputSize, "Output size mismatch");
        for (size_t i = 0; i < OutputSize; ++i) {
            float sum = biases[i];
            const float* row = weights + i * InputSize;
            for (size_t j = 0; j < InputSize; ++j) {
                sum += row[j] * x[j];
            }
            y[i] = sum;
        }
    }

    void update_hash(uint32_t& hash_value) const {
        if (weights) {
            hash_value = fnv1a31_update(
                hash_value,
                reinterpret_cast<const uint8_t*>(weights),
                InputSize * OutputSize * sizeof(float)
            );
        }
        if (biases) {
            hash_value = fnv1a31_update(
                hash_value,
                reinterpret_cast<const uint8_t*>(biases),
                OutputSize * sizeof(float)
            );
        }
    }

private:
    float* weights;
    float* biases;
};

class LocalPolicy {
public:
    LocalPolicy() : loaded(false), module_idx(0), policy_hash(0), sanity_ok(false), build_hash_match(false) {}

    void set_module_index(int idx) {
        if (idx != module_idx) {
            module_idx = idx;
            Serial.printf("[LocalPolicy] Module index set to %d, default_dof_pos = %.4f rad\n",
                          idx, DEPLOY_DEFAULT_DOF_POS[idx]);
        }
    }

    int get_module_index() const { return module_idx; }
    int32_t get_policy_hash() const { return static_cast<int32_t>(policy_hash); }
    bool is_sanity_ok() const { return sanity_ok; }
    bool is_build_hash_match() const { return build_hash_match; }

    bool load_from_littlefs() {
        Serial.println("[LocalPolicy] Mounting LittleFS...");
        if (!LittleFS.begin(true)) {
            Serial.println("[LocalPolicy] ERROR: LittleFS.begin() failed!");
            return false;
        }

        Serial.println("[LocalPolicy] Files in LittleFS:");
        File root = LittleFS.open("/");
        File file = root.openNextFile();
        while (file) {
            Serial.printf("  %s (%u bytes)\n", file.name(), (unsigned)file.size());
            file = root.openNextFile();
        }

        Serial.printf("[LocalPolicy] Loading layer 1 (%zu -> %zu)...\n",
                      LOCAL_INPUT_DIM, LOCAL_H1_DIM);
        if (!fc1.load("/w1.bin", "/b1.bin")) {
            Serial.println("[LocalPolicy] ERROR: fc1 load failed");
            LittleFS.end();
            return false;
        }

        Serial.printf("[LocalPolicy] Loading layer 2 (%zu -> %zu)...\n",
                      LOCAL_H1_DIM, LOCAL_H2_DIM);
        if (!fc2.load("/w2.bin", "/b2.bin")) {
            Serial.println("[LocalPolicy] ERROR: fc2 load failed");
            LittleFS.end();
            return false;
        }

        Serial.printf("[LocalPolicy] Loading layer 3 (%zu -> %zu)...\n",
                      LOCAL_H2_DIM, LOCAL_ACT_DIM);
        if (!fc3.load("/w3.bin", "/b3.bin")) {
            Serial.println("[LocalPolicy] ERROR: fc3 load failed");
            LittleFS.end();
            return false;
        }

        LittleFS.end();
        compute_policy_hash();
        loaded = true;
        sanity_ok = false;
        build_hash_match = (policy_hash == static_cast<uint32_t>(DEPLOY_POLICY_HASH));
        Serial.println("[LocalPolicy] All weights loaded successfully!");
        Serial.printf("[LocalPolicy] Activation: ReLU\n");
        Serial.printf("[LocalPolicy] Policy hash: %ld (0x%08lx)\n",
                      static_cast<long>(policy_hash),
                      static_cast<unsigned long>(policy_hash));
        Serial.printf("[LocalPolicy] Build hash:  %d (match=%s)\n",
                      DEPLOY_POLICY_HASH,
                      build_hash_match ? "YES" : "NO");
        return true;
    }

    bool is_loaded() const { return loaded; }

    float forward_nn(const std::array<float, LOCAL_LATENT_DIM>& latent_cmd,
                     const std::array<float, LOCAL_OBS_DIM>& local_obs) const {
        std::array<float, LOCAL_INPUT_DIM> input{};
        for (size_t i = 0; i < LOCAL_LATENT_DIM; ++i)
            input[i] = latent_cmd[i];
        for (size_t i = 0; i < LOCAL_OBS_DIM; ++i)
            input[LOCAL_LATENT_DIM + i] = local_obs[i];

        std::array<float, LOCAL_H1_DIM> h1{};
        fc1.forward(input, h1);
        for (auto& v : h1) v = local_activation(v);

        std::array<float, LOCAL_H2_DIM> h2{};
        fc2.forward(h1, h2);
        for (auto& v : h2) v = local_activation(v);

        std::array<float, LOCAL_ACT_DIM> out{};
        fc3.forward(h2, out);
        float mean = out[0];

        if (mean < -LOCAL_CLIP_MEAN) mean = -LOCAL_CLIP_MEAN;
        if (mean >  LOCAL_CLIP_MEAN) mean =  LOCAL_CLIP_MEAN;

        float a = tanhf(mean);
        return LOCAL_ACTION_LOW + (a + 1.0f) * 0.5f * (LOCAL_ACTION_HIGH - LOCAL_ACTION_LOW);
    }

    float select_action(const std::array<float, LOCAL_LATENT_DIM>& latent_cmd,
                        const std::array<float, LOCAL_OBS_DIM>& local_obs,
                        float joint_offset) const {
        return forward_nn(latent_cmd, local_obs) + joint_offset;
    }

    float select_action(const std::array<float, LOCAL_LATENT_DIM>& latent_cmd,
                        const std::array<float, LOCAL_OBS_DIM>& local_obs) const {
        return select_action(latent_cmd, local_obs, DEPLOY_DEFAULT_DOF_POS[module_idx]);
    }

    bool run_sanity_check(float expected_mean, float expected_nn_action) {
        Serial.println("\n[LocalPolicy] === Sanity Check ===");

        std::array<float, LOCAL_LATENT_DIM> latent{};
        std::array<float, LOCAL_OBS_DIM> local_obs{};
        if constexpr (LOCAL_LATENT_DIM > 0) {
            latent[0] = 1.0f;
        }
        local_obs[0] = 0.5f;

        std::array<float, LOCAL_INPUT_DIM> input{};
        for (size_t i = 0; i < LOCAL_LATENT_DIM; ++i) input[i] = latent[i];
        for (size_t i = 0; i < LOCAL_OBS_DIM; ++i) input[LOCAL_LATENT_DIM + i] = local_obs[i];

        std::array<float, LOCAL_H1_DIM> h1{};
        fc1.forward(input, h1);
        for (auto& v : h1) v = local_activation(v);

        std::array<float, LOCAL_H2_DIM> h2{};
        fc2.forward(h1, h2);
        for (auto& v : h2) v = local_activation(v);

        std::array<float, LOCAL_ACT_DIM> out{};
        fc3.forward(h2, out);
        float raw_mean = out[0];

        float nn_action = forward_nn(latent, local_obs);
        float motor_target = select_action(latent, local_obs);

        Serial.printf("  Raw mean:       %.8f (expected: %.8f, err: %.2e)\n",
                       raw_mean, expected_mean, fabsf(raw_mean - expected_mean));
        Serial.printf("  NN action:      %.8f (expected: %.8f, err: %.2e)\n",
                       nn_action, expected_nn_action, fabsf(nn_action - expected_nn_action));
        Serial.printf("  + default_dof:  %.4f (module %d)\n",
                       DEPLOY_DEFAULT_DOF_POS[module_idx], module_idx);
        Serial.printf("  Motor target:   %.8f\n", motor_target);

        bool ok = (fabsf(raw_mean - expected_mean) < 1e-3f) &&
                  (fabsf(nn_action - expected_nn_action) < 1e-3f);
        sanity_ok = ok;
        Serial.printf("  Result: %s\n", ok ? "PASS" : "FAIL");

        Serial.println("\n  Per-module motor targets for this test input:");
        for (int m = 0; m < DEPLOY_NUM_MODULES; ++m) {
            Serial.printf("    Module %d: nn_action(%.4f) + default_dof(%.4f) = motor_target(%.4f)\n",
                          m, nn_action, DEPLOY_DEFAULT_DOF_POS[m],
                          nn_action + DEPLOY_DEFAULT_DOF_POS[m]);
        }
        Serial.println("[LocalPolicy] === End Sanity Check ===\n");
        return ok;
    }

private:
    void compute_policy_hash() {
        uint32_t hash_value = 2166136261u;
        fc1.update_hash(hash_value);
        fc2.update_hash(hash_value);
        fc3.update_hash(hash_value);
        policy_hash = hash_value & 0x7fffffffu;
    }

    LocalFC<LOCAL_INPUT_DIM, LOCAL_H1_DIM> fc1;
    LocalFC<LOCAL_H1_DIM, LOCAL_H2_DIM>    fc2;
    LocalFC<LOCAL_H2_DIM, LOCAL_ACT_DIM>   fc3;
    bool loaded;
    int module_idx;
    uint32_t policy_hash;
    bool sanity_ok;
    bool build_hash_match;
};

#endif // LOCAL_POLICY_HPP
