#ifndef LOCAL_POLICY_HPP
#define LOCAL_POLICY_HPP

#include <Arduino.h>
#include <array>
#include <cstdint>
#include <FS.h>
#include <LittleFS.h>
#include "deploy_config.h"
#include "local_obs_config.h"

// ===== Local-only policy network dimensions =====
// Input: local_obs only (no latent)
// Architecture: Linear(input->256) -> ELU -> Linear(256->128) -> ELU -> Linear(128->1)
// Output: tanh(raw) -> action in [-1, 1]
//
// Auto-generated by convert_local_only_to_esp32.py

constexpr size_t LOCAL_INPUT_DIM   = LOCAL_OBS_DIM;  // No latent!
constexpr size_t LOCAL_H1_DIM      = 256;
constexpr size_t LOCAL_H2_DIM      = 128;
constexpr size_t LOCAL_ACT_DIM     = 1;

// ===== ELU activation =====
// ELU activation: f(x) = x if x > 0, else exp(x) - 1
inline float local_activation(float x) {
    return (x > 0.0f) ? x : (expf(x) - 1.0f);
}

// ===== FNV1a hash (for policy identity verification) =====
inline uint32_t fnv1a31_update(uint32_t hash_value, const uint8_t* data, size_t len) {
    for (size_t i = 0; i < len; ++i) {
        hash_value ^= data[i];
        hash_value *= 16777619u;
    }
    return hash_value;
}

// ===== Fully-connected (dense) layer =====
template <size_t InputSize, size_t OutputSize>
class LocalFC {
public:
    LocalFC() : weights(nullptr), biases(nullptr) {}

    ~LocalFC() {
        if (weights) free(weights);
        if (biases) free(biases);
    }

    bool load(const char* weights_path, const char* biases_path) {
        if (!weights) {
            weights = (float*)ps_malloc(InputSize * OutputSize * sizeof(float));
            if (!weights) {
                Serial.println("    WARNING: PSRAM alloc failed, trying heap...");
                weights = (float*)malloc(InputSize * OutputSize * sizeof(float));
                if (!weights) {
                    Serial.printf("    ERROR: Failed to allocate %u bytes for weights\n",
                                  (unsigned)(InputSize * OutputSize * sizeof(float)));
                    return false;
                }
            }
        }

        if (!biases) {
            biases = (float*)ps_malloc(OutputSize * sizeof(float));
            if (!biases) {
                biases = (float*)malloc(OutputSize * sizeof(float));
                if (!biases) {
                    Serial.printf("    ERROR: Failed to allocate %u bytes for biases\n",
                                  (unsigned)(OutputSize * sizeof(float)));
                    return false;
                }
            }
        }

        {
            File f = LittleFS.open(weights_path, "r");
            if (!f) {
                Serial.printf("    ERROR: Cannot open %s\n", weights_path);
                return false;
            }
            const size_t nbytes = InputSize * OutputSize * sizeof(float);
            if (f.size() != nbytes) {
                Serial.printf("    ERROR: %s size %u != expected %u\n",
                              weights_path, (unsigned)f.size(), (unsigned)nbytes);
                f.close();
                return false;
            }
            int rd = f.readBytes(reinterpret_cast<char*>(weights), nbytes);
            f.close();
            if (rd != (int)nbytes) return false;
        }

        {
            File f = LittleFS.open(biases_path, "r");
            if (!f) {
                Serial.printf("    ERROR: Cannot open %s\n", biases_path);
                return false;
            }
            const size_t nbytes = OutputSize * sizeof(float);
            if (f.size() != nbytes) {
                Serial.printf("    ERROR: %s size %u != expected %u\n",
                              biases_path, (unsigned)f.size(), (unsigned)nbytes);
                f.close();
                return false;
            }
            int rd = f.readBytes(reinterpret_cast<char*>(biases), nbytes);
            f.close();
            if (rd != (int)nbytes) return false;
        }

        return true;
    }

    template <size_t N>
    void forward(const std::array<float, InputSize>& x,
                 std::array<float, N>& y) const {
        static_assert(N == OutputSize, "Output size mismatch");
        for (size_t i = 0; i < OutputSize; ++i) {
            float sum = biases[i];
            const float* row = weights + i * InputSize;
            for (size_t j = 0; j < InputSize; ++j) {
                sum += row[j] * x[j];
            }
            y[i] = sum;
        }
    }

    void update_hash(uint32_t& hash_value) const {
        if (weights) {
            hash_value = fnv1a31_update(
                hash_value,
                reinterpret_cast<const uint8_t*>(weights),
                InputSize * OutputSize * sizeof(float)
            );
        }
        if (biases) {
            hash_value = fnv1a31_update(
                hash_value,
                reinterpret_cast<const uint8_t*>(biases),
                OutputSize * sizeof(float)
            );
        }
    }

private:
    float* weights;
    float* biases;
};

// ===== Local-Only Policy =====
// No latent input — the MLP takes only local observations.
// Output: tanh(raw) produces action in [-1, 1].
// Motor target = action * action_scale + joint_offset.
class LocalPolicy {
public:
    LocalPolicy() : loaded(false), module_idx(0), policy_hash(0),
                    sanity_ok(false), build_hash_match(false) {}

    void set_module_index(int idx) {
        if (idx != module_idx) {
            module_idx = idx;
            Serial.printf("[LocalPolicy] Module index set to %d, default_dof_pos = %.4f rad\n",
                          idx, DEPLOY_DEFAULT_DOF_POS[idx]);
        }
    }

    int get_module_index() const { return module_idx; }
    int32_t get_policy_hash() const { return static_cast<int32_t>(policy_hash); }
    bool is_sanity_ok() const { return sanity_ok; }
    bool is_build_hash_match() const { return build_hash_match; }

    bool load_from_littlefs() {
        Serial.println("[LocalPolicy] Mounting LittleFS...");
        if (!LittleFS.begin(true)) {
            Serial.println("[LocalPolicy] ERROR: LittleFS.begin() failed!");
            return false;
        }

        Serial.println("[LocalPolicy] Files in LittleFS:");
        File root = LittleFS.open("/");
        File file = root.openNextFile();
        while (file) {
            Serial.printf("  %s (%u bytes)\n", file.name(), (unsigned)file.size());
            file = root.openNextFile();
        }

        Serial.printf("[LocalPolicy] Loading layer 1 (%zu -> %zu)...\n",
                      LOCAL_INPUT_DIM, LOCAL_H1_DIM);
        if (!fc1.load("/w1.bin", "/b1.bin")) {
            Serial.println("[LocalPolicy] ERROR: fc1 load failed");
            LittleFS.end();
            return false;
        }

        Serial.printf("[LocalPolicy] Loading layer 2 (%zu -> %zu)...\n",
                      LOCAL_H1_DIM, LOCAL_H2_DIM);
        if (!fc2.load("/w2.bin", "/b2.bin")) {
            Serial.println("[LocalPolicy] ERROR: fc2 load failed");
            LittleFS.end();
            return false;
        }

        Serial.printf("[LocalPolicy] Loading layer 3 (%zu -> %zu)...\n",
                      LOCAL_H2_DIM, LOCAL_ACT_DIM);
        if (!fc3.load("/w3.bin", "/b3.bin")) {
            Serial.println("[LocalPolicy] ERROR: fc3 load failed");
            LittleFS.end();
            return false;
        }

        LittleFS.end();
        compute_policy_hash();
        loaded = true;
        sanity_ok = false;
        build_hash_match = (policy_hash == static_cast<uint32_t>(DEPLOY_POLICY_HASH));
        Serial.println("[LocalPolicy] All weights loaded successfully!");
        Serial.printf("[LocalPolicy] Architecture: LOCAL-ONLY (no latent)\n");
        Serial.printf("[LocalPolicy] Activation: ELU\n");
        Serial.printf("[LocalPolicy] Input dim: %zu (obs only)\n", LOCAL_INPUT_DIM);
        Serial.printf("[LocalPolicy] Policy hash: %ld (0x%08lx)\n",
                      static_cast<long>(policy_hash),
                      static_cast<unsigned long>(policy_hash));
        Serial.printf("[LocalPolicy] Build hash:  %d (match=%s)\n",
                      DEPLOY_POLICY_HASH,
                      build_hash_match ? "YES" : "NO");
        return true;
    }

    bool is_loaded() const { return loaded; }

    // Forward pass: local_obs -> raw output -> tanh -> action in [-1, 1]
    float forward_nn(const std::array<float, LOCAL_OBS_DIM>& local_obs) const {
        // Input is just local_obs (no latent concatenation!)
        std::array<float, LOCAL_INPUT_DIM> input{};
        for (size_t i = 0; i < LOCAL_OBS_DIM; ++i)
            input[i] = local_obs[i];

        std::array<float, LOCAL_H1_DIM> h1{};
        fc1.forward(input, h1);
        for (auto& v : h1) v = local_activation(v);

        std::array<float, LOCAL_H2_DIM> h2{};
        fc2.forward(h1, h2);
        for (auto& v : h2) v = local_activation(v);

        std::array<float, LOCAL_ACT_DIM> out{};
        fc3.forward(h2, out);

        // tanh squash: action in [-1, 1]
        return tanhf(out[0]);
    }

    // Convenience: action * scale + joint_offset
    float select_action(const std::array<float, LOCAL_OBS_DIM>& local_obs,
                        float joint_offset) const {
        float action = forward_nn(local_obs);
        return action * DEPLOY_ACTION_SCALE + joint_offset;
    }

    float select_action(const std::array<float, LOCAL_OBS_DIM>& local_obs) const {
        return select_action(local_obs, DEPLOY_DEFAULT_DOF_POS[module_idx]);
    }

    // Backward-compatible overload: accepts (latent, local_obs) but ignores latent
    template <size_t L>
    float forward_nn(const std::array<float, L>& /* latent_cmd */,
                     const std::array<float, LOCAL_OBS_DIM>& local_obs) const {
        return forward_nn(local_obs);  // Ignore latent
    }

    template <size_t L>
    float select_action(const std::array<float, L>& /* latent_cmd */,
                        const std::array<float, LOCAL_OBS_DIM>& local_obs,
                        float joint_offset) const {
        return select_action(local_obs, joint_offset);
    }

    template <size_t L>
    float select_action(const std::array<float, L>& /* latent_cmd */,
                        const std::array<float, LOCAL_OBS_DIM>& local_obs) const {
        return select_action(local_obs);
    }

    bool run_sanity_check(float expected_raw, float expected_action) {
        Serial.println("\n[LocalPolicy] === Sanity Check (local-only) ===");

        std::array<float, LOCAL_OBS_DIM> local_obs{};
        local_obs[0] = 0.5f;  // projected_gravity[0] = 0.5

        std::array<float, LOCAL_INPUT_DIM> input{};
        for (size_t i = 0; i < LOCAL_OBS_DIM; ++i) input[i] = local_obs[i];

        std::array<float, LOCAL_H1_DIM> h1{};
        fc1.forward(input, h1);
        for (auto& v : h1) v = local_activation(v);

        std::array<float, LOCAL_H2_DIM> h2{};
        fc2.forward(h1, h2);
        for (auto& v : h2) v = local_activation(v);

        std::array<float, LOCAL_ACT_DIM> out{};
        fc3.forward(h2, out);
        float raw = out[0];

        float action = tanhf(raw);
        float motor_target = select_action(local_obs);

        Serial.printf("  Raw output:     %.8f (expected: %.8f, err: %.2e)\n",
                       raw, expected_raw, fabsf(raw - expected_raw));
        Serial.printf("  tanh(raw):      %.8f (expected: %.8f, err: %.2e)\n",
                       action, expected_action, fabsf(action - expected_action));
        Serial.printf("  + default_dof:  %.4f (module %d)\n",
                       DEPLOY_DEFAULT_DOF_POS[module_idx], module_idx);
        Serial.printf("  Motor target:   %.8f\n", motor_target);

        bool ok = (fabsf(raw - expected_raw) < 1e-3f) &&
                  (fabsf(action - expected_action) < 1e-3f);
        sanity_ok = ok;
        Serial.printf("  Result: %s\n", ok ? "PASS" : "FAIL");

        Serial.println("\n  Per-module motor targets for this test input:");
        for (int m = 0; m < DEPLOY_NUM_MODULES; ++m) {
            Serial.printf("    Module %d: action(%.4f) * scale(%.1f) + default_dof(%.4f) = motor_target(%.4f)\n",
                          m, action, DEPLOY_ACTION_SCALE, DEPLOY_DEFAULT_DOF_POS[m],
                          action * DEPLOY_ACTION_SCALE + DEPLOY_DEFAULT_DOF_POS[m]);
        }
        Serial.println("[LocalPolicy] === End Sanity Check ===\n");
        return ok;
    }

private:
    void compute_policy_hash() {
        uint32_t hash_value = 2166136261u;
        fc1.update_hash(hash_value);
        fc2.update_hash(hash_value);
        fc3.update_hash(hash_value);
        policy_hash = hash_value & 0x7fffffffu;
    }

    LocalFC<LOCAL_INPUT_DIM, LOCAL_H1_DIM> fc1;
    LocalFC<LOCAL_H1_DIM, LOCAL_H2_DIM>    fc2;
    LocalFC<LOCAL_H2_DIM, LOCAL_ACT_DIM>   fc3;
    bool loaded;
    int module_idx;
    uint32_t policy_hash;
    bool sanity_ok;
    bool build_hash_match;
};

#endif // LOCAL_POLICY_HPP
