; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = jw_esp32

[env:jw_esp32]
platform = espressif32
board = jw_esp32_s3
framework = arduino
lib_ldf_mode = deep
monitor_speed = 115200
; upload_speed = 9600
build_flags =
    -I include
    -I lib/capybarish/examples/pubsub_example
    -DBOARD_HAS_PSRAM
board_build.partitions = default_8MB.csv
board_build.filesystem = littlefs
board_upload.flash_size = 8MB
lib_deps =
    FS
    LittleFS

[env:um_pros3]
platform = espressif32
board = um_pros3
framework = arduino
lib_ldf_mode = deep
monitor_speed = 115200
build_flags = 
    -I include
    -I lib/capybarish/examples/pubsub_example