#ifndef DEPLOY_CONFIG_H
#define DEPLOY_CONFIG_H

// Auto-generated by examples/convert_policy_pkl_to_bin.py
// Source config: real_one_module
//
// Local policy NN architecture:
//   input -> 256 -> 256 -> 1
//
// Inference pipeline on ESP32:
//   1. fused MLP outputs mean
//   2. mean is clipped to [-clip_mean, clip_mean]
//   3. tanh(mean) is unscaled to [action_low, action_high]
//   4. motor_target = nn_action + default_dof_pos[module_idx]

constexpr int DEPLOY_NUM_MODULES = 1;
constexpr int DEPLOY_POLICY_LOOP_HZ = 20;
constexpr int DEPLOY_LOCAL_H1_DIM = 256;
constexpr int DEPLOY_LOCAL_H2_DIM = 256;

// Per-module default joint position offset (radians)
// Module 0: 0.0000 rad
constexpr float DEPLOY_DEFAULT_DOF_POS[1] = {0.000000f};

constexpr float DEPLOY_KP = 8.000000f;
constexpr float DEPLOY_KD = 0.200000f;
constexpr float DEPLOY_ACTION_LOW = -1.200000f;
constexpr float DEPLOY_ACTION_HIGH = 1.200000f;
constexpr float DEPLOY_CLIP_MEAN = 2.000000f;
constexpr float DEPLOY_ACTION_SCALE = 1.000000f;
constexpr float DEPLOY_SYMMETRIC_LIMIT = 0.800000f;
constexpr int DEPLOY_POLICY_HASH = 1783197546;
constexpr float DEPLOY_SANITY_EXPECTED_MEAN = 0.46723765f;
constexpr float DEPLOY_SANITY_EXPECTED_ACTION = 0.52315765f;

#endif // DEPLOY_CONFIG_H
