#ifndef DEPLOY_CONFIG_H
#define DEPLOY_CONFIG_H

// Auto-generated by convert_local_policy_to_bin.py
// Training config: logs/20260307_174442l_lego_tripod/config.yaml
//
// Action pipeline in training:
//   1. Policy outputs raw action in [-symmetric_limit, symmetric_limit]
//   2. action_scaled = raw_action * action_scale
//   3. motor_target = action_scaled + default_dof_pos[module_idx]
//   4. PD control: torque = kp * (motor_target - dof_pos) + kd * (0 - dof_vel)
//
// On ESP32, the local policy NN already outputs in [-0.8, 0.8] (tanh + scale).
// You must add the per-module default_dof_pos AFTER the NN output to get the
// motor position target.

constexpr int DEPLOY_NUM_MODULES = 3;

// Per-module default joint position offset (radians)
// Module 0: 0.0000 rad
// Module 1: 0.5000 rad
// Module 2: -0.5000 rad
constexpr float DEPLOY_DEFAULT_DOF_POS[3] = {0.000000f, 0.500000f, -0.500000f};

// PD gains used in training
constexpr float DEPLOY_KP = 8.0f;
constexpr float DEPLOY_KD = 0.2f;

// Action space bounds
constexpr float DEPLOY_ACTION_SCALE = 1.0f;
constexpr float DEPLOY_SYMMETRIC_LIMIT = 0.8f;
constexpr float DEPLOY_SANITY_EXPECTED_MEAN = -5.09071636f;
constexpr float DEPLOY_SANITY_EXPECTED_ACTION = -0.77122205f;

#endif // DEPLOY_CONFIG_H
