#ifndef DEPLOY_CONFIG_H
#define DEPLOY_CONFIG_H

#include <MotorCtrl.hpp>

// Auto-generated by convert_local_policy_to_bin.py
// Training config: logs/20260330_151153l_randomized_local_imu_next/config.yaml
//
// Local policy NN architecture:
//   input -> 128 -> 64 -> 1
//
// Action pipeline in training:
//   1. Policy outputs raw action in [-symmetric_limit, symmetric_limit]
//   2. action_scaled = raw_action * action_scale
//   3. motor_target = action_scaled + default_dof_pos[module_idx]
//   4. PD control: torque = kp * (motor_target - dof_pos) + kd * (0 - dof_vel)
//
// On ESP32, the local policy NN already outputs in [-0.8000, 0.8000]
// after tanh + rescaling.
// You must add the per-module default_dof_pos AFTER the NN output to get the
// motor position target.

constexpr int DEPLOY_NUM_MODULES = 3;
constexpr int DEPLOY_POLICY_LOOP_HZ = 100;
constexpr int DEPLOY_LOCAL_H1_DIM = 128;
constexpr int DEPLOY_LOCAL_H2_DIM = 64;
constexpr bool DEPLOY_USE_XBOX_CONTROLLER = false;

// Motor deployment config. Override these in the exporter CLI for non-default hardware.
// constexpr Motor_type kMotorType = Motor_type::Cybergear;
// constexpr bool kMotorRequiresZeroCalibration = true;
// constexpr float kMotorFrameOffset = -1.0471975512;
// constexpr float DEPLOY_IMU_FRAME_ROTATION_DEG = -60.0f;


constexpr Motor_type kMotorType = Motor_type::RS03;
constexpr bool kMotorRequiresZeroCalibration = false;
constexpr float kMotorFrameOffset = 0;
constexpr float DEPLOY_IMU_FRAME_ROTATION_DEG = 0.0f;

// Per-module default joint position offset (radians)
// Module 0: 0.0000 rad
// Module 1: 0.5000 rad
// Module 2: -0.5000 rad
constexpr float DEPLOY_DEFAULT_DOF_POS[3] = {0.000000f, 0.500000f, -0.500000f};

// PD gains used by firmware deployment
constexpr float DEPLOY_KP = 8.0f;
constexpr float DEPLOY_KD = 0.2f;

// Motor torque/current limits (applied via Set_parameter in MotorCtrl::Get_state).
// DEPLOY_MAX_TORQUE caps the motor's internal torque output (N·m).
// DEPLOY_MAX_CURRENT caps the motor's q-axis current (A) in position mode.
// Datasheet for RS03: peak torque ≈ 60 N·m, peak current ≈ 90 A.
constexpr float DEPLOY_MAX_TORQUE = 50.0f;
constexpr float DEPLOY_MAX_CURRENT = 43.0f;

// Action space bounds
constexpr float DEPLOY_ACTION_LOW = -0.800000f;
constexpr float DEPLOY_ACTION_HIGH = 0.800000f;
constexpr float DEPLOY_CLIP_MEAN = 2.0f;
constexpr float DEPLOY_ACTION_SCALE = 1.0f;
constexpr float DEPLOY_SYMMETRIC_LIMIT = 0.8f;
constexpr int DEPLOY_POLICY_HASH = 1988983141;
constexpr float DEPLOY_SANITY_EXPECTED_MEAN = -0.45626187f;
constexpr float DEPLOY_SANITY_EXPECTED_ACTION = -0.34162608f;

#endif // DEPLOY_CONFIG_H
