#ifndef LOCAL_OBS_CONFIG_H
#define LOCAL_OBS_CONFIG_H

#include <cstddef>
#include <cstdint>

// Auto-generated by hierarchical/convert_local_policy_to_bin.py

enum class LocalObsField : uint8_t {
    ProjectedGravity,
    Gyro,
    DofPos,
    DofVel,
};

constexpr size_t LOCAL_LATENT_DIM = 8;
constexpr size_t LOCAL_FRAME_HISTORY_STEPS = 5;
constexpr size_t LOCAL_LATENT_HISTORY_STEPS = 5;
constexpr size_t LOCAL_FRAME_COMPONENT_COUNT = 2;
constexpr LocalObsField LOCAL_FRAME_COMPONENTS[LOCAL_FRAME_COMPONENT_COUNT] = {
    LocalObsField::DofPos,
    LocalObsField::DofVel
};
constexpr size_t LOCAL_FRAME_DIM = 2;
constexpr size_t LOCAL_OBS_DIM = 50;

#endif // LOCAL_OBS_CONFIG_H
