[platformio]
default_envs = jw_esp32_infer_bench

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
build_flags =
    -DBOARD_HAS_PSRAM
    -DBENCH_TARGET_HZ=100
    -DBENCH_BURST_ITERATIONS=2000
    -DBENCH_SUSTAINED_CYCLES=300

[env:jw_esp32_infer_bench]
board = jw_esp32_s3

[env:jw_esp32_infer_custom]
board = jw_esp32_s3
build_flags =
    ${env.build_flags}
    -DBENCH_ONLY_CUSTOM_CASE=1
    -DBENCH_CUSTOM_FRAME_DIM=8
    -DBENCH_CUSTOM_HISTORY_STEPS=25
    -DBENCH_CUSTOM_H1_DIM=128
    -DBENCH_CUSTOM_H2_DIM=64

[env:um_pros3_infer_bench]
board = um_pros3
